# ./docker-compose.yml
version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    container_name: php_apache
    volumes:
      - .:/var/www
    ports:
      - "8100:80"